language: java
script: ant release
env: JRE6_HOME=/usr/lib/jvm/java-6-openjdk-amd64/jre
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
sudo: required
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo add-apt-repository -y ppa:apt-fast/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-fast
  - sudo apt-fast -y update
  - sudo apt-fast -m -y --force-yes install lib32z1 lib32ncurses5 wine1.7
