language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk11
    - os: linux
      jdk: oraclejdk8
    - os: osx
      before_install:
        - brew update
        - brew install ant

addons:
  apt:
    packages:
      - wine32

before_install:
  - sudo dpkg --add-architecture i386

before_script:
  - ant -diagnostics

script:
  - ant -noinput -DignoreWineErrors=true
